Repository waliot/rxjs-ru, pull requests merged in 2020-10, with the labels that each got.

#10 Map to operator
  OPERATOR_TEMPLATE.md
  api/operators/pipeable/mapTo.md
Labels: documentation

#11 #4: Добавлена документация для defaultIfEmpty.
  README.md
  api/operators/pipeable/defaultIfEmpty.md
  sidebar.md
Labels: Hacktoberfest

#16 closes #14: Добавлен перевод для оператора pluck
  README.md
  api/operators/pipeable/pluck.md
  sidebar.md
Labels: documentation

#18 closes #17: Добавлен перевод оператора timer
  README.md
  api/operators/creation/timer.md
  sidebar.md
Labels: documentation

#22 Create debounce.md
  README.md
  api/operators/pipeable/debounce.md
  sidebar.md
Labels: documentation

#21 Create delayWhen.md
  README.md
  api/operators/pipeable/delayWhen
  sidebar.md
Labels: documentation

#26 Varrah buffer
  README.md
  api/operators/pipeable/buffer.md
  sidebar.md
Labels: documentation, enhancement

#35 Добавляет перевод оператора zip
  README.md
  api/operators/pipeable/zip.md
  sidebar.md
Labels: документация, улучшение
